### PR TITLE
[nri-bundle] Update Pixie Operator to Helm 3 version

### PR DESCRIPTION
**Pull request by bpschmitt**
#### Is this a new chart

No

#### What this PR does / why we need it:

Removes the Helm 2 version of the Pixie Operator chart and replaces it with the version compatible with Helm 3.

#### Which issue this PR fixes

N/A

#### Special notes for your reviewer:

Also bumped the Infra Operator version in `requirements.yaml`.  It was behind.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (e.g. `[mychartname]`)

### CODE REVIEW

**Comment by paologallinaharbur** [comment]
Hello brad.

We update everything that is not nri-kubernetes-v3 related in the main repo and we fetch and merge the upstream here.

We do not want to have the two repos diverging and the only difference with upstream is in the nri-kubernete chart bundled (to overcome some pipeline limitations). 

Can you do the changes in the main repo?

**Comment by paologallinaharbur** [comment]
Or you were planning to have it under "beta" for a while while we support Helm2?

**Comment by bpschmitt** [comment]
@paologallinaharbur I think the plan was to keep this under Beta for a while.  I had discussed it with @roobre and he suggested I update this repo (unless I misunderstood him).

**Comment by paologallinaharbur** [comment]
I'll sync with him tomorrow to decide how to move with this

**Pull request closed without merging**
